fixup version handling

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -45,15 +45,20 @@ jobs:
         run: |
           set -euo pipefail
           shopt -s extglob
-          if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+)?(\+[0-9A-Za-z-]+)?$ ]]; then
-            echo dry-run=${{ inputs.dry-run != 'false' }}
-            echo version="${VERSION#v}"
-            echo archs='["amd64", "arm64", "arm"]'
-          else
+          if [[ '${{ github.event_name }}' == "pull_request" ]]; then
             echo dry-run=true
             echo version="0.0.0-test.${SHA:0:7}"
             echo archs='["amd64"]'
+            exit 0
           fi >> "$GITHUB_OUTPUT"
+          if ! [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+)?(\+[0-9A-Za-z-]+)?$ ]]; then
+            echo "Invalid version" >&2
+            exit 1
+          fi
+          ( echo dry-run=${{ inputs.dry-run != 'false' }}
+            echo version="${VERSION#v}"
+            echo archs='["amd64", "arm64", "arm"]'
+          ) >> "$GITHUB_OUTPUT"
 
       - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
         if: github.event_name == 'pull_request'
